More descriptive error messages
jhawthorn/discard pull request #108
Opened 2024-07-24 23:04 UTC by Sam-Robin

While working with the discard gem I noticed that you can't discard already discarded records. There wasn't any mention of this in the docs, which cost me some time debugging.

Hopefully this saves others a bit of time :)

2024-07-24 23:05 UTC, Sam-Robin commented on spec/discard/model_spec.rb
> +          }.to raise_error(Discard::RecordNotUndiscarded, "Failed to undiscard the record")
I also noticed this test had the wrong name

2024-07-25 22:25 UTC, jarednorman requested changes
Thanks, this seems like a good change. I just need that typo fixed.

2024-07-25 22:25 UTC, jarednorman commented on lib/discard/model.rb
> +    def disacrded_fail_message
There's a typo in this method name.

2024-07-25 22:25 UTC, jarednorman commented on spec/discard/model_spec.rb
> +        it "raises Discard::RecordNotUndiscarded" do
Nice catch.

2024-07-25 23:12 UTC, Sam-Robin commented on lib/discard/model.rb
> +    def disacrded_fail_message
Fixed

2024-07-29 19:13 UTC, jarednorman commented
Looks good! I will merge this once I've figured out what's going on with CI.

2024-07-29 20:16 UTC, Sam-Robin commented
Thank you! Have a lovely day/afternoon/evening 😄

2024-09-10 23:01 UTC, jhawthorn approved these changes

2024-09-10 23:01 UTC, merged

2024-09-10 23:01 UTC, jhawthorn commented
Thank you!