Wrap discard methods in a transaction
jhawthorn/discard pull request #84
Opened 2022-05-05 19:10 UTC by thewatts

**NOTE:** This PR doesn’t currently include tests (I tested against the provided Ruby script).

Should this code be something you all want in the project, I will by all means add specs 😄 

———

This seeks to solve issue: https://github.com/jhawthorn/discard/issues/77

Given the situation where a `before/after` callback fails, particularly
with related records, we shouldn't still discard records.

Note: This is leveraging a private API that exists in
[ActiveRecord::Transactions](https://github.com/rails/rails/blob/cd2949d2d936daa89b7e23f816f1c004aee85461/activerecord/lib/active_record/transactions.rb#L345)

To run this against the failing spec referenced in the issue (with a few minor adjustments of my own).

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.0"
  gem "sqlite3"
  gem 'discard', github: "thewatts/discard", branch: "nw-transactions"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.datetime :discarded_at
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :text
    t.datetime :discarded_at
  end
end

class Post < ActiveRecord::Base
  include Discard::Model

  has_many :comments

  after_discard do
    comments.discard_all!
  end
end

class Comment < ActiveRecord::Base
  include Discard::Model

  before_discard do
    raise StandardError if text == "RAISE"
  end

  belongs_to :post
end

class BugTest < Minitest::Test
  def test_discard_in_transaction
    post = Post.create!
    post.comments << Comment.create!(text: "KEEP")
    post.comments << Comment.create!(text: "RAISE")

    refute post.comments.any?(&:discarded?)

    begin
      post.discard!
    rescue StandardError => e

    end
    refute post.discarded?
    refute post.comments.any?(&:discarded?)
    assert_empty post.comments.discarded
  end
end
```

2022-05-05 19:58 UTC, willcosgrove requested changes
We discussed this on the phone 📞 which is why I left you no notes 😄

2022-05-05 19:58 UTC, willcosgrove commented on lib/discard/model.rb
> +      raise exception
```suggestion
    rescue
      assign_attributes(self.class.discard_column => previous_discard_value)

      raise
```

2022-05-05 19:58 UTC, willcosgrove commented on lib/discard/model.rb
> +      handle_transaction_rollback(e)
```suggestion
```

2022-05-05 20:21 UTC, thewatts commented
Thanks, @willcosgrove!

2022-05-27 16:02 UTC, GarrisonD commented
Waiting for this MR to get merged soon! 🙂

2022-05-30 14:55 UTC, jarednorman commented
I haven't yet had time to review this to determine if I'm happy with the solution. Feel free to use your the branch directly until I get time. This project merges so few changes that it's unlikely you'll miss out on anything. 🙂

2022-05-30 15:09 UTC, GarrisonD commented
I just wrapped `obj.discard` in a transaction 🙂 need it once so far

2022-11-30 23:29 UTC, egorslam commented
Faced this issue too. For now, wrapped `object.discard` in a transaction.

2022-12-05 20:11 UTC, thewatts commented
@jarednorman friendly bump here 😄

2022-12-05 20:58 UTC, jarednorman requested changes
Aren't AR operations only run in transactions when AR callbacks are present? I don't think we want to wrap _every_ discard in a transaction.

Can you reference how this is done in AR? I'd like to keep the implementation here minimal and in line with _roughly_ how they do it, if we're going to make this change.

2023-03-05 02:24 UTC, thewatts commented
Hey @jarednorman - apologies that I'm just now responding. I missed the fact that you requested changes and responded with a question.

> Aren't AR operations only run in transactions when AR callbacks are present? I don't think we want to wrap every discard in a transaction.

If I understand correctly, all persistence operations are run within a transaction. This is to account for situations like failures as the database level (ex: `null: false` on the field, but the AR model doesn't have a presence validation).

Here's an example:
<img width="574" alt="CleanShot 2023-03-04 at 20 22 23@2x" src="https://user-images.githubusercontent.com/1141717/222938160-f8507c47-06f8-4110-841d-4928622577ae.png">

<img width="1727" alt="CleanShot 2023-03-04 at 20 23 31@2x" src="https://user-images.githubusercontent.com/1141717/222938221-bedca61c-6ccf-4043-9417-ee748f55f54c.png">

You can see in the picture that there's a transaction that is started, and then a rollback on the database error.

---

I'm certainly open to dig into how Rails is exactly handling this, though.

2023-03-05 21:10 UTC, jarednorman commented
Hmmm. I'm struggling to find a reference to when AR uses transactions automatically. If all persistence operations are run in a transaction and discard uses the public persistence API for updating records, then we wouldn't have to do anything for them to be in transactions. It must be something more subtle than that.

2025-01-27 17:11 UTC, timppa23 commented
Nice work with the gem. I think the design is better than in Paranoia.

Just ran into this problem. Looks like discard callbacks don't respect the main object's transaction, which is confusing. 
Calling `foo.discard`

results in following log:
```
  TRANSACTION (0.3ms)  BEGIN
  ↳ app/controllers/api/foos_controller.rb:32:in `destroy'
  Foo Update (0.5ms)  UPDATE "foos" SET "updated_at" = $1, "discarded_at" = $2 WHERE "foos"."id" = $3  [["updated_at", "2025-01-27 16:55:13.706897"], ["discarded_at", "2025-01-27 16:55:13.706294"], ["id", 5]]
  ↳ app/controllers/api/foos_controller.rb:32:in `destroy'
  TRANSACTION (0.8ms)  COMMIT
  ↳ app/controllers/api/foos_controller.rb:32:in `destroy'
  Bar Update All (0.9ms)  UPDATE "bars" SET "bars_id" = $1 WHERE "bars"."foos_id" = $2  [["bar_id", nil], ["foo_id", 5]]
  ↳ app/models/foo.rb:20:in `block in <class:Foo>'
Completed 500 Internal Server Error in 29ms (ActiveRecord: 5.9ms | Allocations: 9816)

ActiveRecord::StatementInvalid - PG::UndefinedColumn: ERROR:  column "bar_id" of relation "bars" does not exist
LINE 1: UPDATE "bars" SET "bar_id" = $1 WH..
```

So to me, it looks like the discard method is already in a transaction, but the after_discard callback doesn't fall under the same transaction. Wrapping the discard into a transaction manually fixes the issue, but it is an ugly solution. 

Thanks for working on this gem!

2026-05-22 11:20 UTC, grncdr commented
> @jarednorman: Hmmm. I'm struggling to find a reference to when AR uses transactions automatically. If all persistence operations are run in a transaction and discard uses the public persistence API for updating records, then we wouldn't have to do anything for them to be in transactions. It must be something more subtle than that.

As mentioned in https://github.com/jhawthorn/discard/issues/77#issuecomment-1002807499, this is implemented by `ActiveRecord::Transactions`. Every call to `#save`/`#update` etc. is wrapped in a transaction using `with_transaction_returning_status`:

https://github.com/rails/rails/blob/84d3c32d026f0807e866907b93be2a3c5786b794/activerecord/lib/active_record/transactions.rb#L382-L384

But because Discard::Model is calling `#update` inside it's own callbacks lifecycle, the `{before,after}_discard` callbacks are called before and after the default AR transaction.

This PR fixes the problem perfectly and should be merged. A major version bump is probably warranted if you want to be extra paranoid.

2026-05-25 22:37 UTC, jarednorman commented
Sure, if this PR gets rebased and the conflict gets fixed, I can merge an release a new major version.

---

Also, hello @grncdr. It has been a very, very long time since I've seen you. Hope you're well!

2026-05-27 20:36 UTC, jarednorman commented
Closing in favour of #124.

2026-05-27 20:36 UTC, closed without merging